defaults:
  - default
  - _self_

experiment_name: 'debug'
save_dir: 'output'

data:
  data_dir: 'data/panda_radboud/pp_slides'
  train_csv: 'data/panda_radboud/train.csv'
  tune_csv: 'data/panda_radboud/tune.csv'
  test_csv: 'data/panda_radboud/test.csv'
  filetype: '.jpg'

training:
  num_classes: 2
  epochs: 1
  lr: 2e-4
  tile_size: 3200
  train_set_size: 0.01

tuning:
  tune_set_size: 0.01
  tracking: 'auc'

speed:
  num_workers: 1